-- ============================================================================
-- FINAL CONSOLIDATED POSTGRESQL SCHEMA FOR SUPABASE
-- Project Target : MidProjectSE (Supabase PostgreSQL)
-- Description    : DDL, DML Seed, Alterations, and Identity Synchronization
-- Target Schema  : public
-- ============================================================================

-- ----------------------------------------------------------------------------
-- 1. Create Table: users
-- ----------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS users (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    full_name VARCHAR(100) NOT NULL,
    username VARCHAR(50) NOT NULL UNIQUE,
    email VARCHAR(100) NOT NULL UNIQUE,
    password VARCHAR(255) NOT NULL,
    role VARCHAR(20) NOT NULL,
    status VARCHAR(20) NOT NULL DEFAULT 'ACTIVE',
    phone VARCHAR(20),
    department VARCHAR(100),
    avatar VARCHAR(255),
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

-- ----------------------------------------------------------------------------
-- 2. Create Table: reports
-- ----------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS reports (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    reporter_id BIGINT NOT NULL,
    title VARCHAR(200),
    location VARCHAR(255) NOT NULL,
    category VARCHAR(100),
    description TEXT NOT NULL,
    urgency VARCHAR(20) DEFAULT 'MEDIUM',
    status VARCHAR(30) NOT NULL DEFAULT 'PENDING_VERIFICATION',
    rejection_reason TEXT,
    notes TEXT,
    assigned_staff_id BIGINT,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    approved_at TIMESTAMP NULL,
    processed_at TIMESTAMP NULL,
    resolved_at TIMESTAMP NULL,
    CONSTRAINT fk_report_reporter FOREIGN KEY (reporter_id) REFERENCES users (id) ON DELETE CASCADE,
    CONSTRAINT fk_report_assigned_staff FOREIGN KEY (assigned_staff_id) REFERENCES users (id) ON DELETE SET NULL
);

-- ----------------------------------------------------------------------------
-- 3. Create Table: report_images
-- ----------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS report_images (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    report_id BIGINT NOT NULL,
    file_name VARCHAR(255) NOT NULL,
    file_path TEXT NOT NULL,
    file_type VARCHAR(100),
    file_size BIGINT,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_report_image_report FOREIGN KEY (report_id) REFERENCES reports (id) ON DELETE CASCADE
);

-- ----------------------------------------------------------------------------
-- 4. Seed Initial Users (password: password123 for all dev accounts)
-- ----------------------------------------------------------------------------
INSERT INTO users (id, full_name, username, email, password, role, status, phone, department, avatar, created_at)
VALUES 
(1, 'Budi Santoso', 'budi_santoso', 'user@kebersihan.id', '$2a$10$IGw6.z.z77k5b2WBZtEuJu5QCW/GoEVcNYiXc/LdLKDTcVNxxivwi', 'USER', 'ACTIVE', '081234567890', 'Fakultas Teknik / Mahasiswa', 'https://images.unsplash.com/photo-1535713875002-d1d0cf377fde?w=150', NOW()),
(2, 'Ani Wijaya', 'ani_wijaya', 'ani@kebersihan.id', '$2a$10$IGw6.z.z77k5b2WBZtEuJu5QCW/GoEVcNYiXc/LdLKDTcVNxxivwi', 'USER', 'ACTIVE', '081298765432', 'Fakultas Ekonomi / Dosen', 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=150', NOW()),
(3, 'Rudi Hermawan', 'rudi_petugas', 'staff@kebersihan.id', '$2a$10$IGw6.z.z77k5b2WBZtEuJu5QCW/GoEVcNYiXc/LdLKDTcVNxxivwi', 'STAFF', 'ACTIVE', '082155551234', 'Divisi Kebersihan Gedung A & B', 'https://images.unsplash.com/photo-1570295999919-56ceb5ecca61?w=150', NOW()),
(4, 'Agus Prasetyo', 'agus_petugas', 'staff2@kebersihan.id', '$2a$10$IGw6.z.z77k5b2WBZtEuJu5QCW/GoEVcNYiXc/LdLKDTcVNxxivwi', 'STAFF', 'ACTIVE', '082166667890', 'Divisi Kebersihan Gedung C & Luar', 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=150', NOW()),
(5, 'Super Administrator', 'admin_utama', 'admin@kebersihan.id', '$2a$10$IGw6.z.z77k5b2WBZtEuJu5QCW/GoEVcNYiXc/LdLKDTcVNxxivwi', 'ADMIN', 'ACTIVE', '081122334455', 'Biro Fasilitas & Manajemen Gedung', 'https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?w=150', NOW())
ON CONFLICT (id) DO NOTHING;

-- ----------------------------------------------------------------------------
-- 5. Seed Initial Reports (Sample Reports with all 5 status states)
-- ----------------------------------------------------------------------------
INSERT INTO reports (id, reporter_id, title, location, category, description, urgency, status, rejection_reason, notes, assigned_staff_id, created_at, approved_at, processed_at, resolved_at)
VALUES
(1, 1, 'Tumpahan Minuman & Sampah Plastik di Koridor', 'Gedung A - Lantai 2 (Ruang Kuliah A201 - A208)', 'Lobi & Koridor', 'Terdapat tumpahan kopi manis yang lengket di depan pintu masuk Ruang A204 dan beberapa gelas plastik berserakan.', 'HIGH', 'PENDING_VERIFICATION', NULL, NULL, NULL, NOW() - INTERVAL '2 hours', NULL, NULL, NULL),
(2, 2, 'Papan Tulis Penuh Coretan & Penghapus Berdebu', 'Gedung A - Lantai 3 (Laboratorium Komputer)', 'Ruang Kelas / Kuliah', 'Papan tulis di lab A302 belum dibersihkan dan penghapus sudah berdebu tebal.', 'MEDIUM', 'APPROVED', NULL, NULL, NULL, NOW() - INTERVAL '5 hours', NOW() - INTERVAL '4 hours', NULL, NULL),
(3, 2, 'Wastafel Mampet & Genangan Air di Toilet Pria', 'Gedung C - Lantai 1 (Toilet Utama Pria & Wanita)', 'Toilet / Kamar Mandi', 'Wastafel nomor 2 tersumbat tisu dan air meluap hingga membasahi lantai toilet pria.', 'HIGH', 'PROCESSING', NULL, 'Petugas sedang membersihkan sumbatan wastafel dan mengeringkan lantai toilet.', 3, NOW() - INTERVAL '6 hours', NOW() - INTERVAL '5 hours', NOW() - INTERVAL '3 hours', NULL),
(4, 1, 'Tempat Sampah Organik & Anorganik Penuh Meluap', 'Gedung B - Lantai 1 (Kantin & Area Terbuka)', 'Kantin / Food Court', 'Tempat sampah di area makan barat kantin sudah meluap karena jam makan siang.', 'MEDIUM', 'RESOLVED', NULL, 'Sudah disterilkan dengan disinfektan dan diganti kantong sampah tebal 60L.', 4, NOW() - INTERVAL '24 hours', NOW() - INTERVAL '23 hours', NOW() - INTERVAL '22 hours', NOW() - INTERVAL '20 hours'),
(5, 1, 'Foto Tidak Jelas dan Lokasi Tidak Lengkap', 'Area Parkir Barat', 'Lainnya', 'Ada kotoran di sudut dekat parkir motor.', 'LOW', 'REJECTED', 'Foto tidak jelas dan deskripsi lokasi kurang spesifik untuk ditindaklanjuti petugas.', NULL, NULL, NOW() - INTERVAL '12 hours', NULL, NULL, NULL)
ON CONFLICT (id) DO NOTHING;

-- ----------------------------------------------------------------------------
-- 6. Seed Initial Report Images
-- ----------------------------------------------------------------------------
INSERT INTO report_images (id, report_id, file_name, file_path, file_type, file_size, created_at)
VALUES
(1, 1, 'tumpahan_kopi.jpg', 'https://images.unsplash.com/photo-1618221195710-dd6b41faaea6?w=800&auto=format&fit=crop&q=80', 'image/jpeg', 358400, NOW() - INTERVAL '2 hours'),
(2, 2, 'papan_tulis.jpg', 'https://images.unsplash.com/photo-1580582932707-520aed937b7b?w=800&auto=format&fit=crop&q=80', 'image/jpeg', 421000, NOW() - INTERVAL '5 hours'),
(3, 3, 'wastafel_mampet.jpg', 'https://images.unsplash.com/photo-1584622650111-993a426fbf0a?w=800&auto=format&fit=crop&q=80', 'image/jpeg', 512000, NOW() - INTERVAL '6 hours'),
(4, 4, 'tempat_sampah.jpg', 'https://images.unsplash.com/photo-1532996122724-e3c354a0b15b?w=800&auto=format&fit=crop&q=80', 'image/jpeg', 298000, NOW() - INTERVAL '24 hours'),
(5, 5, 'foto_buram.jpg', 'https://images.unsplash.com/photo-1581578731548-c64695cc6952?w=800&auto=format&fit=crop&q=80', 'image/jpeg', 180000, NOW() - INTERVAL '12 hours')
ON CONFLICT (id) DO NOTHING;

-- ----------------------------------------------------------------------------
-- 7. Add Columns: building and room (V6 Migration equivalent)
-- ----------------------------------------------------------------------------
ALTER TABLE reports
ADD COLUMN IF NOT EXISTS building VARCHAR(50) NULL,
ADD COLUMN IF NOT EXISTS room VARCHAR(150) NULL;

-- ----------------------------------------------------------------------------
-- 8. Backfill Existing Records for building and room (Exact V6 logic)
-- ----------------------------------------------------------------------------
UPDATE reports
SET building = CASE 
    WHEN id = 1 THEN 'GK1'
    WHEN id = 2 THEN 'GK2'
    WHEN id = 3 THEN 'GK3'
    WHEN id = 4 THEN 'GA'
    WHEN id = 5 THEN 'PARKING_LOT'
    ELSE 'OTHER'
END,
room = CASE
    WHEN id = 1 THEN 'Lantai 2 Koridor Ruang Kuliah 204'
    WHEN id = 2 THEN 'Laboratorium Komputer 302'
    WHEN id = 3 THEN 'Toilet Pria Lantai 1'
    WHEN id = 4 THEN 'Kantin & Area Terbuka'
    WHEN id = 5 THEN 'Area Parkir Barat'
    WHEN location IS NOT NULL AND location != '' THEN location
    ELSE 'Area Kampus'
END
WHERE building IS NULL OR room IS NULL;

-- ----------------------------------------------------------------------------
-- 9. Apply NOT NULL Constraints on building and room
-- ----------------------------------------------------------------------------
ALTER TABLE reports
ALTER COLUMN building SET NOT NULL,
ALTER COLUMN room SET NOT NULL;

-- ----------------------------------------------------------------------------
-- 10. Synchronize PostgreSQL Identity Sequences after manual ID seeding
-- ----------------------------------------------------------------------------
SELECT setval(pg_get_serial_sequence('users', 'id'), COALESCE((SELECT MAX(id) FROM users), 1));
SELECT setval(pg_get_serial_sequence('reports', 'id'), COALESCE((SELECT MAX(id) FROM reports), 1));
SELECT setval(pg_get_serial_sequence('report_images', 'id'), COALESCE((SELECT MAX(id) FROM report_images), 1));
